### PR TITLE
Added the option to specify a subPath

### PR DESCRIPTION
**Pull request by gandazgul**
I'm using this to share a config and data volume across multiple pods

### CODE REVIEW

**Comment by munnerz** [comment]
Can you add a commented out option to the chart's values.yaml, to help users find this?

Thanks for the PR! 😄

**Comment by gandazgul** [comment]
Will do, hopefully today.

**Comment by billimek** [comment]
#34 created to complete this

**Comment by munnerz** [comment]
Thanks @gandazgul and @billimek!

**Comment by gandazgul** [comment]
Omg thank you. I totally forgot about this.

**Pull request closed without merging**
