### PR TITLE
Allow to specify "access mode" to data pvc

### PR DESCRIPTION
**Pull request by casidiablo**

### CODE REVIEW

**Comment by onedr0p** [comment]
Does this mean that there is no default now?

**Comment by casidiablo** [comment]
It means that right now it is hardcoded to `ReadWriteMany`, and you can't change it from values.yaml.

**Review by simplyzee — CHANGES_REQUESTED** [review]
Thanks for the PR @casidiablo. Please could you include the default value of `ReadWriteMany` set within the values.yaml file and some documentation to reflect the change. At least this way, a default value is set but is customisable via the chart. 🙂

**Comment by casidiablo** [comment]
Done

**Comment by simplyzee** [comment]
Thanks @casidiablo for contributing. Another good improvement made to kube-plex.

**Pull request merged**
