### PR TITLE
Added the ability to specify custom volumes and volume mounts

### PR DESCRIPTION
**Pull request by gandazgul**
I also improved the docs for subpath in values.yaml and added examples for volume mounts and volumes.

### CODE REVIEW

**Comment by cybervoid** [comment]
@gandazgul Any progress with this? I'm also needing this feature, it would be nice to have...

**Comment by gandazgul** [comment]
This PR fixes #21

**Comment by denebeim** [comment]
This update is not sufficient to do what it wants to do.  I was going to implement basically this same thing, but it's way more complicated than that.  Look at the generatePod function in the main.go file.  The way that pods are being spawned in this code is not going to allow you to have custom anythings.

**Comment by gandazgul** [comment]
In a follow up PR I was going to take a look at the pod generation logic and have it follow the same logic as the parent pod instead of having a template hard coded but, this solved my issue for now (I'm not using the separate encoding pods and no one seemed interested in the change so I forked this repo and made some other changes I needed.

**Pull request closed without merging**
