### PR TITLE
different persistence accessmodes for config files

### PR DESCRIPTION
**Pull request by billimek**
Certain backend storage solutions (e.g. ceph rbd) don't allow ReadWriteMany accessModes.

The purpose of this PR is to allow users to choose the accessMode they want to use.

### CODE REVIEW

**Comment by munnerz** [comment]
If we allow this (and especially so if we make it the new default), it will break the 'kube-plex' autoscaling functionality, as the `config` PVC needs to be mounted into each transcoder pod as well as the main plex pod: https://github.com/munnerz/kube-plex/blob/8ff5b97832c7b2e6e97c3830c22747093c6d3e0c/main.go#L147-L154

I think we're limited as to what we can do here, barring making setting this to anything except ReadWriteMany mutually exclusive with `kubePlex.enabled=true` 🤔

**Comment by billimek** [comment]
aha, this is a good point!  At the very least, the default should go back to `ReadWriteMany` - I'll push that change, it should have remained the same by default all-along.

I do think it's important to allow usage of this with PVs that simply aren't allowed to use ReadWriteMany.  

Are you ok with me making some changes (and documentation) to this to make `ReadWriteMany` mutually-exclusive with `kubePlex.enabled`, as you suggest, or does that overly-complicate things?

**Comment by jgilfoil** [comment]
Any chance of this getting merged? I'd also like to be able to run this in a local lab environment with simple hostpath shares until i'm ready to migrate it to something more "production ready".

**Comment by jgilfoil** [comment]
thanks!

**Pull request merged**
