### PR TITLE
Fix the kube-plex copy script for plexpass images

### PR DESCRIPTION
**Pull request by gandazgul**
The script currently set to run as a postStart container fails on the plexpass docker image because there's no plex built-in. This image downloads plex when it starts so that it evergreen. My change here is to add the lines to copy kube-plex to the update script at the end, this way it gets run after plex is installed.

### CODE REVIEW

**Comment by gandazgul** [comment]
@munnerz What do you think of this change?

**Comment by munnerz** [comment]
`set -e` causes the script to error if any of its subcommands error.

Your change here will cause the script to silently absorb failures, hence why this 'works'.

In reality, this will cause the `kubePlex` integration not to work.

Based on the log output you've provided, it sounds like the "Plex Transcoder" binary is not at `/usr/lib/plexmediaserver/` - could you have a look in the plexpass version of the image to work out where this should actually be placed?

**Comment by gandazgul** [comment]
I can put the set -e back but removing it wasn't the change. The thing with the plaxpass image is that there's no plex built in it so running your script as a postStart will always fail. 

When it starts the container downloads and installs the latest version of plex. The change I made is to override the command ("/init") with copying the commands to copy kube-plex to Plex Transcoder to the update script and then calling init so that they run once plex is done installing.

**Comment by gandazgul** [comment]
I do get an error creating the pod:

2018/11/28 23:03:49 Error waiting for pod to complete: pod "pms-elastic-transcoder-n8bbc" failed
2018/11/28 23:03:49 Cleaning up pod...

But I havent had time to look into why it can't create it, do you know where to look?

**Comment by gandazgul** [comment]
> I do get an error creating the pod:
> 
> 2018/11/28 23:03:49 Error waiting for pod to complete: pod "pms-elastic-transcoder-n8bbc" failed
> 2018/11/28 23:03:49 Cleaning up pod...
> 
> But I havent had time to look into why it can't create it, do you know where to look?

I found the issue, this is unrelated. the problem is that I mount my data volume with subPath but the transcoder pod is created without the subPath so it can't find the file to transcode. I will investigate a solution for this but its unrelated to this PR.

**Comment by gandazgul** [comment]
@munnerz what do you think about this change now?

**Comment by cybervoid** [comment]
I have plex pass and just had an issue with an update with the plex pass version. Any way we can get this changes done?

**Comment by scruplelesswizard** [comment]
If I understand correctly, the Plex Pass containers update Plex _within_ the running container. I can't think of any Kubernetes lifecycle hooks that could handle this, something within the update mechanism of Plex would have to handle executing the commands to re-inject kube-plex

If I am misunderstanding something can you please clarify?

**Comment by gandazgul** [comment]
@chaosaffe yes you are right. Nothing in kubernetes will trigger this automatically. I've been updating by deleting the pod and letting the deployment recreate it. But without this change kubeplex fails and it never gets injected so it's not really related to the upgrade mechanism just to where the Plex pass image stores the files.

**Comment by ElanHasson** [comment]
A sidecar container could mount the folder and wait for the files to appear before it begins working, then sleep forever.

**Comment by gandazgul** [comment]
At this point I'm just going to merge this on my fork and continue to use it there. I'm not sure why this simple change is such a contender.

**Pull request closed without merging**
